export type StatKey = "insight" | "empathy" | "order" | "bond";

export type StoryStats = Record<StatKey, number>;

export type StoryFlag =
  | "early_fact_path"
  | "early_human_path"
  | "early_balance_path"
  | "early_fact_recheck"
  | "early_human_recheck"
  | "early_balance_recheck"
  | "c3_design_time_axis_flag"
  | "c3_design_relation_axis_flag"
  | "c3_final_fact_report"
  | "c3_final_motive_report"
  | "c3_final_balanced_report"
  | "c4_board_procedure"
  | "c4_board_witness"
  | "c4_board_public_risk"
  | "c4_hearing_reliability_order"
  | "c4_hearing_exception_prevention"
  | "c4_witness_trust_focus"
  | "c4_witness_log_pair"
  | "c4_press_reform_first"
  | "c4_press_repair_first"
  | "c4_resolution_strict"
  | "c4_resolution_repair"
  | "c4_resolution_balanced"
  | "panel_censure"
  | "panel_reconciliation"
  | "panel_reform"
  | "prebrief_record_chain"
  | "prebrief_witness_circle"
  | "prebrief_rule_review"
  | "rumor_media_strategy"
  | "rumor_public_forum"
  | "rumor_internal_discipline"
  | "summary_internal_notice"
  | "summary_public_trust"
  | "summary_followup_schedule"
  | "c5_frame_evidence_chain"
  | "c5_frame_testimony_context"
  | "c5_frame_public_balance"
  | "c7_panel_core_testimony"
  | "c7_panel_audit_record"
  | "c7_panel_expert_reform"
  | "c7_cross_procedure_answer"
  | "c7_cross_recovery_answer"
  | "c7_cross_summary_answer"
  | "verdict_censure"
  | "verdict_reconciliation"
  | "verdict_reform";

export type StoryFlagState = Partial<Record<StoryFlag, boolean>> & Record<string, boolean | undefined>;

export type BackgroundKey =
  | "office"
  | "forest"
  | "village"
  | "maze"
  | "return"
  | "panel_room"
  | "evidence_board"
  | "hearing_room"
  | "review_room"
  | "public_forum"
  | "censure_chamber"
  | "reconciliation_desk"
  | "reform_blueprint"
  | "cctv_room"
  | "rule_archive"
  | "witness_room"
  | "forest_crossroads"
  | "server_room"
  | "archive_log"
  | "map_room"
  | "guard_post";

export type Choice = {
  choiceId?: string;
  label: string;
  subtext?: string;
  next: string;
  effects?: Partial<StoryStats>;
  evidence?: string;
  setFlags?: Partial<Record<StoryFlag, boolean>>;
};

export type StoryNode = {
  id: string;
  chapter: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  scene:
    | "office"
    | "forest"
    | "village"
    | "maze"
    | "return"
    | "archive"
    | "hearing"
    | "panel"
    | "cctv"
    | "witness"
    | "press"
    | "censure"
    | "reconciliation"
    | "reform";
  backgroundKey?: BackgroundKey;
  location: string;
  speaker: string;
  text: string;
  next?: string;
  choices?: Choice[];
  evidence?: string;
  setFlags?: Partial<Record<StoryFlag, boolean>>;
  document?: boolean;
  ending?: "balanced" | "human" | "order";
};

export const EVIDENCE: Record<string, { title: string; description: string; mark: string }> = {
  double_id: {
    title: "이중 계정 기록",
    description: "한 사람이 두 개의 신원으로 접근한 정황과 타임스탬프 정합을 정리한 단서.",
    mark: "ID",
  },
  torn_affiliation: {
    title: "조직 소속 단서",
    description: "로그에서 발견한 소속 표기의 변경 흔적과 예외 구간 요약.",
    mark: "AF",
  },
  five_links: {
    title: "연결 고리 다섯 개",
    description: "출입, 통화, 승인, 문서, 증언을 한 번에 연결해 본 상호 정합 점검.",
    mark: "L5",
  },
  voice_name: {
    title: "목격자 음성명",
    description: "녹취에서 식별 단서와 이름 혼동 구간을 분리한 기록.",
    mark: "VO",
  },
  rule_note: {
    title: "규정 검토 메모",
    description: "해당 사건의 해당 조항과 예외 규정을 비교 정리한 내부 메모.",
    mark: "RM",
  },
  internal_log: {
    title: "내부 로그",
    description: "시스템이 남긴 출입·승인·수정 타임라인 초안.",
    mark: "LG",
  },
  staff_interview: {
    title: "직원 증언 정리",
    description: "직원 진술을 재정렬하고 모순 가능 구간을 강조한 기록.",
    mark: "SI",
  },
  security_camera: {
    title: "보안 카메라 캡처",
    description: "감시 구간의 핵심 캡처를 시간순으로 정렬한 증거.",
    mark: "SC",
  },
  admin_ledgers: {
    title: "관리자 장부",
    description: "승인 경로의 중간 승인자와 수정 흔적을 확인한 장부 로그.",
    mark: "AL",
  },
};

export const CHAPTERS = {
  1: {
    title: "CHAPTER 1: 이상한 출발선",
    subtitle: "한 조각의 기록에서 시작되는 사건의 첫 결정을 찾는다.",
  },
  2: {
    title: "CHAPTER 2: 숲의 흔적",
    subtitle: "시간과 증언이 엮인 초기 정황의 교차점을 찾는다.",
  },
  3: {
    title: "CHAPTER 3: 마을의 언어",
    subtitle: "언어 규약과 내부 기록의 간극을 번역해 본다.",
  },
  4: {
    title: "CHAPTER 4: 규정의 미로",
    subtitle: "규범과 예외의 경계를 한 장면씩 정리한다.",
  },
  5: {
    title: "CHAPTER 5: 공개 청문회",
    subtitle: "심의의 마지막 구간에서 균형안을 설계한다.",
  },
  6: {
    title: "CHAPTER 6: 사전 검토",
    subtitle: "재확인과 조치안을 조합해 불확실성을 정리한다.",
  },
  7: {
    title: "CHAPTER 7: 최종 심의",
    subtitle: "최종 청문 앞에서 증거와 판단을 결합한다.",
  },
};

export const STORY: Record<string, StoryNode> = {
  c1_open: {
    id: "c1_open",
    chapter: 1,
    scene: "office",
    location: "사무실 로비",
    speaker: "하린",
    text: "문이 열리고, 긴급 사건 알림이 뜬다. 오늘은 내부 접근 이력 이상 징후를 조사해야 하는 날. 증거를 쪼개서 읽을지, 전체 흐름으로 볼지는 네 선택이다.",
    next: "c1_briefing",
  },

  c1_briefing: {
    id: "c1_briefing",
    chapter: 1,
    scene: "office",
    location: "사무실 회의실",
    speaker: "하치",
    text: "하린, 오늘 조사 대상은 입구 로그가 아닌, 출입 로그의 맥락이다. 시간대별 단서 조합이 핵심이다.",
    next: "c1_case_intro",
    document: true,
  },

  c1_case_intro: {
    id: "c1_case_intro",
    chapter: 1,
    scene: "office",
    location: "사무실 브리핑 데스크",
    speaker: "나레이터",
    text: "이 사건은 단순한 실수로 보이지만, 데이터가 얽힌 방식은 이상하다. 기록은 있어도 결말이 없다. 네가 묶어내야 한다.",
    choices: [
      {
        choiceId: "c1_seed_fact_path",
        label: "로그를 먼저 정리한다",
        subtext: "시간순 정렬로 단서 간 모순을 찾는다",
        next: "c1_logs",
        effects: { insight: 1, order: 1 },
        evidence: "internal_log",
        setFlags: { early_fact_path: true },
      },
      {
        choiceId: "c1_seed_human_path",
        label: "직원 진술부터 확인한다",
        subtext: "증언에서 사람의 흔적과 동선을 추적한다",
        next: "c1_staff_intro",
        effects: { empathy: 2 },
        evidence: "staff_interview",
        setFlags: { early_human_path: true },
      },
      {
        choiceId: "c1_seed_balance_path",
        label: "규정부터 펼쳐 본다",
        subtext: "우선 정책 위반 가능성을 좁힌다",
        next: "c1_rules",
        effects: { order: 2 },
        evidence: "rule_note",
        setFlags: { early_balance_path: true },
      },
    ],
  },

  c1_logs: {
    id: "c1_logs",
    backgroundKey: "server_room",
    chapter: 1,
    scene: "office",
    location: "사무실 데이터 데스크",
    speaker: "하린",
    text: "첫 번째 열람은 출입 로그이다. 누군가가 같은 시간에 둘 이상의 창구를 거친 흔적이 보인다.",
    next: "c1_mid_a",
    evidence: "internal_log",
    document: true,
  },
  c1_mid_a: {
    id: "c1_mid_a",
    backgroundKey: "server_room",
    chapter: 1,
    scene: "office",
    location: "사무실 데이터 데스크",
    speaker: "하치",
    text: "로그의 간격이 일정치 않다. 같은 아이디가 다른 장비에서 짧은 간격으로 이동했다는 건 수동 조작 전조일 수 있다.",
    next: "c1_mid_b",
  },
  c1_mid_b: {
    id: "c1_mid_b",
    backgroundKey: "server_room",
    chapter: 1,
    scene: "office",
    location: "사무실 데이터 데스크",
    speaker: "하린",
    text: "이건 우선순위가 낮은 오류라 치부하기엔 위험하다. 다음 정거장으로 넘어가 세부 기록을 확인하자.",
    next: "c1_transition_to_ch2",
    document: true,
  },

  c1_staff_intro: {
    id: "c1_staff_intro",
    backgroundKey: "witness_room",
    chapter: 1,
    scene: "office",
    location: "사무실 상담실",
    speaker: "하린",
    text: "진술은 즉시 모순을 드러낸다. 같은 증언이 다른 시간대에 서로 다른 책임자를 가리킨다.",
    next: "c1_staff_b",
    document: true,
    evidence: "staff_interview",
  },
  c1_staff_b: {
    id: "c1_staff_b",
    backgroundKey: "witness_room",
    chapter: 1,
    scene: "office",
    location: "사무실 상담실",
    speaker: "하치",
    text: "한 명의 목소리를 고정해 두고 보면, 3분짜리 공백이 반복된다. 증언 단서만으로는 결정을 못 한다.",
    next: "c1_staff_c",
  },
  c1_staff_c: {
    id: "c1_staff_c",
    backgroundKey: "witness_room",
    chapter: 1,
    scene: "office",
    location: "사무실 상담실",
    speaker: "하린",
    text: "좋아, 지금은 사람의 기억이 아니라 시간의 빈칸을 맞추는 단계다. 기록 정렬로 다시 가보자.",
    next: "c1_transition_to_ch2",
    effects: { empathy: 1, order: 1 },
  },

  c1_rules: {
    id: "c1_rules",
    chapter: 1,
    scene: "office",
    location: "사무실 규정 아카이브",
    speaker: "하린",
    text: "규정 초안을 펼치면 반례가 먼저 보인다. 예외 조항이 작동한 순간부터 사건은 더 늦게만 풀린다.",
    next: "c1_rules_b",
    evidence: "rule_note",
    document: true,
  },
  c1_rules_b: {
    id: "c1_rules_b",
    chapter: 1,
    scene: "office",
    location: "사무실 규정 아카이브",
    speaker: "하치",
    text: "단서가 규정보다 많아지면 탐문해야 한다. 다음 구역은 과거 기록이 쌓인 숲 구역이다.",
    next: "c1_transition_to_ch2",
    effects: { order: 1 },
  },

  c1_transition_to_ch2: {
    id: "c1_transition_to_ch2",
    chapter: 1,
    scene: "office",
    location: "사무실 복도",
    speaker: "나레이터",
    text: "1장 조사가 마무리되자 보조 동선이 드러난다. 다음은 숲 구역의 저장 기록이다.",
    next: "c2_arrival",
    document: true,
  },

  c2_arrival: {
    id: "c2_arrival",
    chapter: 2,
    scene: "forest",
    location: "기록 보관 숲 입구",
    speaker: "나레이터",
    text: "숲 구역은 오래된 데이터와 새 로그가 겹쳐 있는 장소다. 첫 시점마다 문서와 음성 기록이 미묘하게 어긋난다.",
    next: "c2_keeper",
    document: true,
  },

  c2_keeper: {
    id: "c2_keeper",
    chapter: 2,
    scene: "forest",
    backgroundKey: "village",
    location: "보관실 입구",
    speaker: "하치",
    text: "출입 기록은 여기에서 더 조각난다. 입구마다 다르게 기록되는 항목이 하나씩 연결돼야 한다.",
    next: "c2_maze_gate",
  },
  c2_maze_gate: {
    id: "c2_maze_gate",
    chapter: 2,
    scene: "village",
    backgroundKey: "village",
    location: "과거 기록의 문",
    speaker: "하린",
    text: "문은 조그맣게 떨리며 열리고, 분기점이 3개로 갈라진다. 먼저 어떤 기록을 우선적으로 처리할까.",
    next: "c2_maze_split",
  },

  c2_maze_split: {
    id: "c2_maze_split",
    chapter: 2,
    scene: "village",
    backgroundKey: "village",
    location: "분기점",
    speaker: "나레이터",
    text: "여기서 선택이 길이 된다. 같은 목적을 향해 가도 증거의 순서가 달라져 결과가 달라진다.",
    choices: [
      {
        choiceId: "c2_seed_fact_path",
        label: "로그를 더 깊게 파고들어 시간축을 복원한다",
        subtext: "시간 구간의 누락과 중복을 확인한다",
        next: "c2_log_node",
        effects: { insight: 2 },
        evidence: "double_id",
        setFlags: { early_fact_recheck: true },
      },
      {
        choiceId: "c2_seed_balance_path",
        label: "지점표시를 다시 확인해 우회 경로를 고른다",
        subtext: "동선 지도와 규칙 경로를 비교한다",
        next: "c2_waypoint",
        effects: { order: 1 },
        setFlags: { early_balance_recheck: true },
      },
      {
        choiceId: "c2_seed_human_path",
        label: "보안 근무 기록을 확인해 경비 체계까지 추적한다",
        subtext: "교대표의 빈 구간과 담당자 변경을 추적한다",
        next: "c2_guard_shift",
        effects: { empathy: 1, insight: 1 },
        setFlags: { early_human_recheck: true },
      },
    ],
  },

  c2_log_node: {
    id: "c2_log_node",
    chapter: 2,
    scene: "archive",
    backgroundKey: "archive_log",
    location: "과거 기록 보관소",
    speaker: "하린",
    text: "시간축은 꼬인 실 같았다. 동일한 이벤트가 서로 다른 순서로 저장되어 있었고, 그 차이에서 조작 흔적이 보인다.",
    next: "c2_log_detail",
    document: true,
  },
  c2_log_detail: {
    id: "c2_log_detail",
    chapter: 2,
    scene: "village",
    backgroundKey: "archive_log",
    location: "과거 기록 보관소",
    speaker: "하치",
    text: "세 번째 구간만 다르게 기록돼 있다. 여기엔 임시 승인 코드가 삽입되어 있어야 했는데 삭제된 채로 남아 있다.",
    next: "c2_log_crosscheck",
  },
  c2_log_crosscheck: {
    id: "c2_log_crosscheck",
    chapter: 2,
    scene: "village",
    backgroundKey: "archive_log",
    location: "과거 기록 실험실",
    speaker: "하린",
    text: "교차 검증으로 빈칸을 채우면, 이번 분기에서 가장 오래된 누락 타임스탬프가 드러난다.",
    next: "c2_maze_gate_exit",
    evidence: "internal_log",
  },

  c2_waypoint: {
    id: "c2_waypoint",
    chapter: 2,
    scene: "village",
    backgroundKey: "map_room",
    location: "지도 구획 표식",
    speaker: "나레이터",
    text: "지도에 표시된 길은 서로 겹치지 않는다. 첫 번째 지점은 출입 기록, 두 번째는 승인 기록이다.",
    next: "c2_waypoint_map",
  },
  c2_waypoint_map: {
    id: "c2_waypoint_map",
    chapter: 2,
    scene: "village",
    backgroundKey: "map_room",
    location: "지도 구획 표식",
    speaker: "하치",
    text: "표식의 각 점에서 담당자 이름이 바뀌어 있는데, 변경 이력과 교대 정보가 일치하지 않는다.",
    next: "c2_waypoint_stack",
    evidence: "torn_affiliation",
  },
  c2_waypoint_stack: {
    id: "c2_waypoint_stack",
    chapter: 2,
    scene: "village",
    backgroundKey: "map_room",
    location: "지도 비교실",
    speaker: "하린",
    text: "한 번 더 겹치기를 하면, 우회로의 끝점이 내부 승인 라인으로 바뀐다. 정규 동선만으로는 도달할 수 없는 지점이다.",
    next: "c2_maze_gate_exit",
    evidence: "rule_note",
  },

  c2_guard_shift: {
    id: "c2_guard_shift",
    chapter: 2,
    scene: "village",
    backgroundKey: "guard_post",
    location: "경비 교대 로그존",
    speaker: "하치",
    text: "교대 기록은 대부분 정합적이지만, 한 명의 지문이 다른 교대에 맞물려 있다. 2번 교대가 비정상적으로 짧다.",
    next: "c2_guard_shift_notes",
  },
  c2_guard_shift_notes: {
    id: "c2_guard_shift_notes",
    chapter: 2,
    scene: "village",
    backgroundKey: "guard_post",
    location: "경비 교대 로그존",
    speaker: "하린",
    text: "2차 보안 담당자 로그는 원본과 다르게 편집돼 있다. 이건 사람의 실수라기보다 의도적 개입처럼 보인다.",
    next: "c2_guard_shift_interview",
    evidence: "internal_log",
  },
  c2_guard_shift_interview: {
    id: "c2_guard_shift_interview",
    chapter: 2,
    scene: "village",
    backgroundKey: "guard_post",
    location: "보안 대화 기록실",
    speaker: "하치",
    text: "교대표 증언을 열면 시간 공백이 두 번 반복된다. 여기서 얻은 단서를 다음 단계로 넘겨야 한다.",
    next: "c2_maze_gate_exit",
    evidence: "voice_name",
  },

  c2_maze_gate_exit: {
    id: "c2_maze_gate_exit",
    chapter: 2,
    scene: "village",
    location: "다시 갈림길로",
    speaker: "나레이터",
    text: "3개의 경로를 모두 점검했기에 규정 미로로 진입할 준비가 됐다. 다음은 제도 해석이 필요한 본론 구간이다.",
    next: "early_route_gate",
    document: true,
  },

  c3_entry_fact: {
    id: "c3_entry_fact",
    chapter: 3,
    scene: "maze",
    backgroundKey: "server_room",
    location: "로그 우선 진입로",
    speaker: "하린",
    text: "지금까지의 선택은 시간표와 원본 로그를 먼저 붙잡는 방향이었다. 미로는 사람보다 기록의 순서로 먼저 열리고, 첫 질문도 누가 아니라 언제가 된다.",
    next: "c3_entry_fact_followup",
    document: true,
  },
  c3_entry_human: {
    id: "c3_entry_human",
    chapter: 3,
    scene: "maze",
    backgroundKey: "witness_room",
    location: "증언 우선 진입로",
    speaker: "하치",
    text: "지금까지의 선택은 진술과 회복 가능성을 먼저 보호하는 방향이었다. 미로는 기록의 빈칸보다 사람의 기억이 왜 어긋났는지를 먼저 묻는다.",
    next: "c3_entry_human_followup",
    document: true,
  },
  c3_entry_balanced: {
    id: "c3_entry_balanced",
    chapter: 3,
    scene: "maze",
    backgroundKey: "rule_archive",
    location: "균형 검토 진입로",
    speaker: "나레이터",
    text: "지금까지의 선택은 규정과 맥락을 함께 비교하는 방향이었다. 미로는 한쪽 증거만 따라가면 닫히고, 서로 다른 기준을 나란히 세울 때 다음 문을 연다.",
    next: "c3_entry_balanced_followup",
    document: true,
  },
  c3_entry_mixed: {
    id: "c3_entry_mixed",
    chapter: 3,
    scene: "maze",
    backgroundKey: "evidence_board",
    location: "혼합 단서 진입로",
    speaker: "나레이터",
    text: "지금까지의 선택은 한 방향으로 모이지 않았다. 기록, 증언, 규정이 서로 다른 문을 가리키고 있어, 미로는 먼저 충돌 지점을 표시한 뒤 다음 질문을 연다.",
    next: "c3_entry_mixed_followup",
    document: true,
  },

  c3_entry_fact_followup: {
    id: "c3_entry_fact_followup",
    chapter: 3,
    scene: "maze",
    backgroundKey: "server_room",
    location: "로그 우선 확인대",
    speaker: "하린",
    text: "분기 결과는 바로 사라지지 않는다. 첫 조사표에는 원본 로그, 출입 시각, 통보 순서가 굵게 표시되고, 이후 미로 해석도 이 기록 순서를 기준으로 시작된다.",
    next: "c3_entry",
    document: true,
  },
  c3_entry_human_followup: {
    id: "c3_entry_human_followup",
    chapter: 3,
    scene: "maze",
    backgroundKey: "witness_room",
    location: "증언 우선 확인대",
    speaker: "해치",
    text: "분기 결과는 바로 사라지지 않는다. 첫 조사표에는 당사자 진술, 감정선, 설명 순서가 굵게 표시되고, 이후 미로 해석도 진술 충돌을 먼저 풀어내며 시작된다.",
    next: "c3_entry",
    document: true,
  },
  c3_entry_balanced_followup: {
    id: "c3_entry_balanced_followup",
    chapter: 3,
    scene: "maze",
    backgroundKey: "rule_archive",
    location: "균형 검토 확인대",
    speaker: "나레이터",
    text: "분기 결과는 바로 사라지지 않는다. 첫 조사표에는 규정 조항, 맥락 메모, 비교 기준이 나란히 표시되고, 이후 미로 해석도 한쪽 결론으로 서두르지 않는다.",
    next: "c3_entry",
    document: true,
  },
  c3_entry_mixed_followup: {
    id: "c3_entry_mixed_followup",
    chapter: 3,
    scene: "maze",
    backgroundKey: "evidence_board",
    location: "혼합 단서 확인대",
    speaker: "하린",
    text: "조사표는 특정 성향 대신 충돌 목록을 먼저 남긴다. 이후 미로 해석은 하나의 정답을 향해 뛰지 않고, 서로 맞지 않는 단서를 따로 보존한 상태로 시작된다.",
    next: "c3_entry",
    document: true,
  },
  c3_entry: {
    id: "c3_entry",
    chapter: 3,
    scene: "maze",
    location: "규정의 미로 입구",
    speaker: "나레이터",
    text: "미로 앞엔 정수기처럼 반복되는 표식이 있다. 세 개의 안내문이 다른 답을 가리킨다. 무엇부터 열어야 하나.",
    next: "c3_system",
    document: true,
  },
  c3_system: {
    id: "c3_system",
    chapter: 3,
    scene: "maze",
    location: "규정 인터페이스",
    speaker: "시스템",
    text: "현재 탐색 모드는 '자료 수집'이다. A: 출입/승인 이력, B: 시스템 예외 규정, C: 직원 신원 교차검증 순으로 제안한다.",
    next: "c3_system_route",
    document: true,
  },
  c3_system_route: {
    id: "c3_system_route",
    chapter: 3,
    scene: "maze",
    location: "규정 인터페이스",
    speaker: "나레이터",
    text: "각 경로가 서로 다른 조각을 제공한다. 하나만 골라도 되지만, 오래 가려면 세 경로를 모두 비교해야 한다.",
    choices: [
      {
        label: "A를 먼저 따라 출입/승인 데이터부터 정리한다",
        subtext: "기본 시간축 정합을 빠르게 맞춘다",
        next: "c3_system_route_a",
        effects: { insight: 1 },
      },
      {
        label: "B를 먼저 열고 예외 규정의 적용 범위를 재확인한다",
        subtext: "과도한 예외가 규칙을 위반했는지 본다",
        next: "c3_system_route_b",
        effects: { order: 1 },
      },
      {
        label: "C를 먼저 확인해 음성 식별 단서를 재확인한다",
        subtext: "목격자 단서의 신뢰도를 점검한다",
        next: "c3_system_route_c",
        effects: { empathy: 1 },
      },
    ],
  },

  c3_system_route_a: {
    id: "c3_system_route_a",
    chapter: 3,
    scene: "maze",
    location: "규정 인터페이스",
    speaker: "하린",
    text: "출입 기록과 승인 승인자명이 달라지는 순간이 최소 2회 관측된다. 이 단계에서 시간 불일치가 완성된다.",
    next: "c3_system_route_a2",
  },
  c3_system_route_a2: {
    id: "c3_system_route_a2",
    chapter: 3,
    scene: "maze",
    location: "규정 인터페이스",
    speaker: "하치",
    text: "첫 번째 차이점은 마지막 통로에서 발생한다. 출입 승인자와 실제 사용자가 매치되지 않는다.",
    next: "c3_interview",
    document: true,
    evidence: "double_id",
  },

  c3_system_route_b: {
    id: "c3_system_route_b",
    chapter: 3,
    scene: "maze",
    location: "규정 인터페이스",
    speaker: "시스템",
    text: "예외 규정은 분기마다 서로 다른 기간을 적용한다. 규정 충돌이 빈번하면, 누군가 승인 단계에서 조작했을 수 있다.",
    next: "c3_system_route_b2",
    effects: { order: 1 },
    evidence: "rule_note",
  },
  c3_system_route_b2: {
    id: "c3_system_route_b2",
    chapter: 3,
    scene: "maze",
    location: "규정 인터페이스",
    speaker: "하치",
    text: "예외 기간이 너무 넓다. 정상 운영이라면 이곳은 자동 경보가 나야 하지만, 흔적은 의도적으로 조용히 둬졌다.",
    next: "c3_interview",
    document: true,
  },

  c3_system_route_c: {
    id: "c3_system_route_c",
    chapter: 3,
    scene: "maze",
    location: "규정 인터페이스",
    speaker: "하린",
    text: "음성 단서는 짧지만 강한 신호를 남긴다. 같은 이름을 가진 두 사람이 2분 간격으로 바뀐 흔적이 있다.",
    next: "c3_system_route_c2",
    evidence: "voice_name",
  },
  c3_system_route_c2: {
    id: "c3_system_route_c2",
    chapter: 3,
    scene: "maze",
    location: "규정 인터페이스",
    speaker: "하치",
    text: "음성 텍스트가 시간축과 한 번씩 어긋난다. 여기서부터 직접 면담으로 넘어가야만 결론이 선명해진다.",
    next: "c3_interview",
    document: true,
    effects: { empathy: 1 },
  },

  c3_interview: {
    id: "c3_interview",
    chapter: 3,
    scene: "maze",
    location: "심층 면담실",
    speaker: "하치",
    text: "면담실 문이 열리며 네가 찾던 단서가 한꺼번에 떠오른다. 먼저 어떤 방향으로 질문을 뽑을지 고른다.",
    document: true,
    choices: [
      {
        label: "일정표의 공백이 왜 생겼는지부터 묻는다",
        subtext: "교대와 승인 간의 연결 부위를 집중 점검",
        next: "c3_interview_branch_a",
        effects: { order: 2, empathy: 1 },
      },
      {
        label: "증거의 연결 고리를 다시 맞춘다",
        subtext: "로그/승인/음성의 순서를 재검증",
        next: "c3_interview_branch_b",
        effects: { insight: 2, empathy: 1 },
        evidence: "five_links",
      },
      {
        label: "직원 진술의 공통점과 차이를 비교한다",
        subtext: "목격자 진술 변동 구간에 집중",
        next: "c3_interview_branch_c",
        effects: { empathy: 2, order: 1 },
      },
    ],
  },

  c3_interview_branch_a: {
    id: "c3_interview_branch_a",
    chapter: 3,
    scene: "maze",
    location: "심층 면담실",
    speaker: "나레이터",
    text: "공백의 원인을 좁히자, 특정 교대와 특정 승인만 반복된 사실이 보인다.",
    next: "c3_interview_follow_a",
    effects: { order: 1 },
  },
  c3_interview_branch_b: {
    id: "c3_interview_branch_b",
    chapter: 3,
    scene: "maze",
    location: "심층 면담실",
    speaker: "나레이터",
    text: "연결 고리를 다시 묶자 증거 열이 한 방향으로 수렴한다. 누군가 특정 시점부터 서열을 바꿔놓은 것 같다.",
    next: "c3_interview_follow_b",
    effects: { insight: 1 },
    evidence: "five_links",
  },
  c3_interview_branch_c: {
    id: "c3_interview_branch_c",
    chapter: 3,
    scene: "maze",
    location: "심층 면담실",
    speaker: "나레이터",
    text: "직원 진술은 큰 줄기는 맞지만, 결론 문구만 자주 바뀐다. 기록이 아닌 사람의 의도에서 원인을 잡아야 한다.",
    next: "c3_interview_follow_c",
    effects: { empathy: 1, bond: 1 },
  },

  c3_interview_follow_a: {
    id: "c3_interview_follow_a",
    chapter: 3,
    scene: "maze",
    location: "심층 면담실",
    speaker: "하린",
    text: "추가 질의에서 첫 번째 증언이 실험실 기록과 완전히 일치한다. 남은 건 최종 정리 뿐이다.",
    next: "c3_design",
  },
  c3_interview_follow_b: {
    id: "c3_interview_follow_b",
    chapter: 3,
    scene: "maze",
    location: "심층 면담실",
    speaker: "하린",
    text: "연결 정합이 완료됐다. 승인자 변경 포인트를 중심으로 면담 내용이 다시 맞춰졌다.",
    evidence: "rule_note",
    document: true,
    next: "c3_design",
  },
  c3_interview_follow_c: {
    id: "c3_interview_follow_c",
    chapter: 3,
    scene: "maze",
    location: "심층 면담실",
    speaker: "하린",
    text: "진술의 핵심만 남기면 결함은 한 명에게 집중된다. 사람의 책임 구간이 명확해지는 순간이다.",
    next: "c3_design",
  },

  c3_design: {
    id: "c3_design",
    chapter: 3,
    scene: "maze",
    location: "규정 설계실",
    speaker: "하치",
    text: "이제 수집 데이터로 설계안을 만든다. 어떤 진술이 최종 보고서에 들어가야 하는지 선별해야 한다.",
    next: "c3_design_review",
  },
  c3_design_review: {
    id: "c3_design_review",
    chapter: 3,
    scene: "maze",
    location: "규정 설계실",
    speaker: "하린",
    text: "한 번의 정리로는 모순이 남는다. 2회 검증 후 최종 요약을 작성한다.",
    document: true,
    choices: [
      {
        choiceId: "c3_design_time_axis",
        label: "시간축 정합을 우선한다",
        subtext: "내부 로그의 타임라인만 먼저 마감",
        next: "c3_design_summary",
        effects: { insight: 1 },
        evidence: "internal_log",
        setFlags: { c3_design_time_axis_flag: true },
      },
      {
        choiceId: "c3_design_relation_axis",
        label: "인물 관계 정합을 우선한다",
        subtext: "증언과 승인 관계를 먼저 결합",
        next: "c3_design_relation_summary",
        effects: { empathy: 1, order: 1 },
        evidence: "staff_interview",
        setFlags: { c3_design_relation_axis_flag: true },
      },
    ],
  },
  c3_design_summary: {
    id: "c3_design_summary",
    chapter: 3,
    scene: "maze",
    backgroundKey: "evidence_board",
    location: "규정 설계실",
    speaker: "하치",
    text: "시간축으로 닫은 요약본은 공백의 위치를 먼저 보여준다. 심사실에는 누가 언제 기록을 비웠는지부터 전달된다.",
    effects: { insight: 2, order: 1 },
    evidence: "internal_log",
    document: true,
    next: "c3_final",
  },
  c3_design_relation_summary: {
    id: "c3_design_relation_summary",
    chapter: 3,
    scene: "maze",
    backgroundKey: "reconciliation_desk",
    location: "규정 설계실",
    speaker: "하린",
    text: "관계 정합으로 닫은 요약본은 말이 바뀐 지점보다 왜 말이 바뀌었는지를 앞세운다. 심사실에는 책임 구간과 완화 사유가 함께 전달된다.",
    evidence: "staff_interview",
    document: true,
    next: "c3_final",
  },
  c3_final: {
    id: "c3_final",
    chapter: 3,
    scene: "maze",
    location: "최종 전달 구간",
    speaker: "시스템",
    text: "네 정리가 4장 심사 단계로 넘어간다. 남은 증거는 네 판단에 따라 최종 결론을 바꾼다.",
    document: true,
    choices: [
      {
        choiceId: "c3_final_strict_report",
        label: "시간-승인-증언 순으로 바로 정리된 보고서를 제출한다",
        subtext: "사실 중심으로만 구성된 결론 경로",
        next: "c4_return_fact_notice",
        effects: { order: 3, empathy: -2 },
        evidence: "internal_log",
        setFlags: { c3_final_fact_report: true },
      },
      {
        choiceId: "c3_final_motive_report",
        label: "인물의 동기와 책임 구간을 먼저 강조한 완화안으로 제출한다",
        subtext: "후속 조치의 선처를 남긴다",
        next: "c4_return_motive_notice",
        effects: { empathy: 3, order: -1 },
        evidence: "staff_interview",
        setFlags: { c3_final_motive_report: true },
      },
      {
        choiceId: "c3_final_balanced_report",
        label: "규정, 진술, 로그를 3박자 동기화로 제시한다",
        subtext: "균형형 결론으로 심사 리스크를 줄인다",
        next: "c4_return_balanced_notice",
        effects: { insight: 2, empathy: 1, order: 2, bond: 1 },
        evidence: "rule_note",
        setFlags: { c3_final_balanced_report: true },
      },
    ],
  },

  c4_return_fact_notice: {
    id: "c4_return_fact_notice",
    chapter: 4,
    scene: "office",
    backgroundKey: "evidence_board",
    location: "사무실 복귀 통로",
    speaker: "하치",
    text: "보고서는 시간표처럼 접혔다. 심사위원이 처음 보게 될 화면은 로그 공백과 승인 순서다.",
    next: "c4_return_fact_followup",
    evidence: "internal_log",
    document: true,
  },
  c4_return_motive_notice: {
    id: "c4_return_motive_notice",
    chapter: 4,
    scene: "office",
    backgroundKey: "reconciliation_desk",
    location: "사무실 복귀 통로",
    speaker: "하린",
    text: "완화안은 사람의 맥락을 전면에 둔다. 기록보다 먼저 들리는 것은 왜 그 공백이 방치됐는지에 대한 설명이다.",
    next: "c4_return_motive_followup",
    evidence: "staff_interview",
    document: true,
  },
  c4_return_balanced_notice: {
    id: "c4_return_balanced_notice",
    chapter: 4,
    scene: "office",
    backgroundKey: "panel_room",
    location: "사무실 복귀 통로",
    speaker: "시스템",
    text: "균형 보고서는 규정, 진술, 로그를 같은 폭으로 나란히 놓는다. 어느 한쪽이 밀리면 결론도 바로 흔들린다.",
    next: "c4_return_balanced_followup",
    evidence: "rule_note",
    document: true,
  },
  c4_return_fact_followup: {
    id: "c4_return_fact_followup",
    chapter: 4,
    scene: "office",
    backgroundKey: "evidence_board",
    location: "사실 공지 확인석",
    speaker: "하린",
    text: "복귀 후 첫 화면에는 로그 공백과 승인 순서가 고정된다. 심사 준비는 사람의 의도보다 기록의 빈칸을 먼저 설명하는 흐름으로 이어진다.",
    next: "c4_return_notice",
    document: true,
  },
  c4_return_motive_followup: {
    id: "c4_return_motive_followup",
    chapter: 4,
    scene: "office",
    backgroundKey: "reconciliation_desk",
    location: "동기 설명 확인석",
    speaker: "해치",
    text: "복귀 후 첫 화면에는 당사자 설명과 방치된 맥락이 고정된다. 심사 준비는 규정 위반만이 아니라 왜 그런 선택이 나왔는지부터 묻는다.",
    next: "c4_return_notice",
    document: true,
  },
  c4_return_balanced_followup: {
    id: "c4_return_balanced_followup",
    chapter: 4,
    scene: "office",
    backgroundKey: "panel_room",
    location: "균형 공지 확인석",
    speaker: "나레이터",
    text: "복귀 후 첫 화면에는 규정, 진술, 로그가 같은 폭으로 고정된다. 심사 준비는 어느 한쪽을 지우지 않고 비교표를 유지한 채 진행된다.",
    next: "c4_return_notice",
    document: true,
  },
  c4_return_notice: {
    id: "c4_return_notice",
    backgroundKey: "office",
    chapter: 4,
    scene: "office",
    location: "사무실 복귀 통로",
    speaker: "하린",
    text: "4장 심사실로 이동한다. 이곳에서 증거를 공개하고, 서로 다른 주장들을 공식 기록으로 바꿔야 한다.",
    next: "c4_arrive_night",
    document: true,
  },
  c4_arrive_night: {
    id: "c4_arrive_night",
    backgroundKey: "hearing_room",
    chapter: 4,
    scene: "office",
    location: "심야 심사실 앞",
    speaker: "나레이터",
    text: "심사실은 조용하다. 하지만 각 증거 노드의 조합이 곧 판결의 방향이 된다.",
    next: "c4_briefing",
    document: true,
  },
  c4_briefing: {
    id: "c4_briefing",
    backgroundKey: "hearing_room",
    chapter: 4,
    scene: "office",
    location: "심사 브리핑 룸",
    speaker: "하치",
    text: "마지막 분기다. 증거를 공개할 채널을 고르면 다음 작업이 달라진다.",
    choices: [
      {
        label: "로그 정리 라인으로 전체 타임라인을 제시한다",
        subtext: "출입 로그와 승인 기록을 중심으로 공개",
        next: "c4_log_room",
        effects: { insight: 2 },
        evidence: "internal_log",
      },
      {
        label: "감사 아카이브 라인으로 내부 대조표를 제시한다",
        subtext: "규정 예외와 승인 변경 지점을 공개",
        next: "c4_audit_room",
        effects: { order: 2, empathy: -1 },
      },
      {
        label: "진술 중심 라인으로 증인 기록을 먼저 제출한다",
        subtext: "직원 진술을 중심으로 신뢰성 판정을 유도",
        next: "c4_witness_room",
        effects: { empathy: 2 },
        evidence: "staff_interview",
      },
    ],
  },

  c4_log_room: {
    id: "c4_log_room",
    backgroundKey: "server_room",
    chapter: 4,
    scene: "office",
    location: "로그 검토실",
    speaker: "나레이터",
    text: "로그를 먼저 풀면 타임라인이 선명해진다. 숨겨진 공백이 줄지어 보인다.",
    next: "c4_log_audit",
    evidence: "internal_log",
    document: true,
  },
  c4_log_audit: {
    id: "c4_log_audit",
    backgroundKey: "server_room",
    chapter: 4,
    scene: "office",
    location: "로그 검토실",
    speaker: "하치",
    text: "공백 구간의 책임 주체를 3개로 압축하면 전체 사건의 동선이 성립한다.",
    next: "c4_security_camera",
  },
  c4_security_camera: {
    id: "c4_security_camera",
    chapter: 4,
    scene: "cctv",
    backgroundKey: "cctv_room",
    location: "보안 카메라룸",
    speaker: "나레이터",
    text: "카메라 캡처는 로그와 맞물린다. 마지막에 누락된 영상이 의도적으로 삭제된 흔적이 분명하다.",
    next: "c4_board_pre",
    evidence: "security_camera",
    document: true,
  },

  c4_audit_room: {
    id: "c4_audit_room",
    chapter: 4,
    scene: "archive",
    backgroundKey: "archive_log",
    location: "감사 아카이브",
    speaker: "하치",
    text: "감사 장부는 정합이 빠르다. 하지만 규정과 예외의 분기마다 누군가 다른 기준을 적용했다.",
    next: "c4_audit_gap",
    evidence: "rule_note",
    document: true,
  },
  c4_audit_gap: {
    id: "c4_audit_gap",
    chapter: 4,
    scene: "office",
    location: "감사 아카이브",
    speaker: "나레이터",
    text: "중간 관리자의 승인 흔적이 두 갈래로 갈린다. 한 쪽은 빈칸, 다른 쪽은 임시 승인이다.",
    next: "c4_audit_cross",
    document: true,
    evidence: "admin_ledgers",
  },
  c4_audit_cross: {
    id: "c4_audit_cross",
    chapter: 4,
    scene: "office",
    location: "감사 교차 검토실",
    speaker: "하린",
    text: "교차 검토 결과, 장부의 이슈를 면담과 함께 제시해야 판정이 무너지 않는다.",
    next: "c4_board_pre",
  },

  c4_witness_room: {
    id: "c4_witness_room",
    chapter: 4,
    scene: "office",
    location: "진술 보관실",
    speaker: "하린",
    text: "증언은 신뢰를 얻어야 힘이 생긴다. 반복된 진술 속 진심과 오차를 분리한다.",
    next: "c4_witness_interview",
  },
  c4_witness_interview: {
    id: "c4_witness_interview",
    chapter: 4,
    scene: "office",
    location: "진술 보관실",
    speaker: "나레이터",
    text: "한 목소리가 공통된 시간에만 바뀌는 패턴을 보이면, 문서 조작보다는 전달 누락이 큰 듯하다.",
    next: "c4_witness_followup",
    evidence: "staff_interview",
  },
  c4_witness_followup: {
    id: "c4_witness_followup",
    chapter: 4,
    scene: "office",
    location: "진술 보관실",
    speaker: "하치",
    text: "추가 면담으로 핵심 진술만 남기고, 오해를 줄인다. 최종 제출물은 지금의 결론이다.",
    next: "c4_board_pre",
    document: true,
  },

  c4_board_pre: {
    id: "c4_board_pre",
    backgroundKey: "hearing_room",
    chapter: 4,
    scene: "office",
    location: "심사위원회 대기실",
    speaker: "하린",
    text: "이제 결론 패널로 들어가기 전 단계다. 마지막으로 방식만 정하면 된다.",
    choices: [
      {
        choiceId: "c4_board_pre_procedure",
        label: "엄격한 절차에 따라 증거 정합부터 제시한다",
        subtext: "심사 우선순위를 증거로 제시",
        next: "c4_hearing_prepare",
        effects: { order: 2, insight: 1 },
        evidence: "rule_note",
        setFlags: { c4_board_procedure: true },
      },
      {
        choiceId: "c4_board_pre_witness",
        label: "진술/증거 동시 제시 방식으로 간결하게 정리한다",
        subtext: "심사자의 이해도를 높이는 서술형 보고",
        next: "c4_witness_prepare",
        effects: { empathy: 2, insight: 1 },
        evidence: "staff_interview",
        setFlags: { c4_board_witness: true },
      },
      {
        choiceId: "c4_board_pre_public_risk",
        label: "대외 발표 문안처럼 압축해 영향과 위험도 우선 제시한다",
        subtext: "향후 재발 방지까지 담은 제언 포함",
        next: "c4_press_plan",
        effects: { order: -1, empathy: 2 },
        evidence: "double_id",
        setFlags: { c4_board_public_risk: true },
      },
    ],
  },

  c4_hearing_prepare: {
    id: "c4_hearing_prepare",
    backgroundKey: "hearing_room",
    chapter: 4,
    scene: "hearing",
    location: "심사 사전 준비실",
    speaker: "하치",
    text: "절차 중심 요약은 강하다. 다만 과도한 엄격함은 상대의 반발을 부를 수 있다.",
    choices: [
      {
        choiceId: "c4_hearing_reliability_order",
        label: "증거의 신뢰도 순으로 3단계 발표를 구성한다",
        subtext: "심사위원의 판단 부담을 낮춘다",
        next: "c4_hearing_evidence_order",
        effects: { order: 1 },
        evidence: "admin_ledgers",
        setFlags: { c4_hearing_reliability_order: true },
      },
      {
        choiceId: "c4_hearing_exception_prevention",
        label: "예외와 규정 충돌을 먼저 노출하고 예방법을 제시한다",
        subtext: "설명 가능성에 초점을 둔 제시",
        next: "c4_hearing_exception_order",
        effects: { empathy: 1 },
        evidence: "rule_note",
        setFlags: { c4_hearing_exception_prevention: true },
      },
    ],
  },
  c4_hearing_evidence_order: {
    id: "c4_hearing_evidence_order",
    chapter: 4,
    scene: "office",
    backgroundKey: "cctv_room",
    location: "심사 사전 준비실",
    speaker: "나레이터",
    text: "카메라, 로그, 장부 순으로 증거가 세워진다. 이 순서는 심사자의 질문을 사람보다 기록 쪽으로 먼저 끌고 간다.",
    next: "c4_hearing_order",
    evidence: "admin_ledgers",
    document: true,
  },
  c4_hearing_exception_order: {
    id: "c4_hearing_exception_order",
    chapter: 4,
    scene: "office",
    backgroundKey: "rule_archive",
    location: "심사 사전 준비실",
    speaker: "하린",
    text: "예외 조항을 먼저 펼치자 심사실의 공기가 달라진다. 잘못을 묻기 전에 왜 같은 예외가 반복됐는지부터 따진다.",
    next: "c4_hearing_order",
    evidence: "rule_note",
    document: true,
  },
  c4_hearing_order: {
    id: "c4_hearing_order",
    backgroundKey: "hearing_room",
    chapter: 4,
    scene: "office",
    location: "심사 사전 준비실",
    speaker: "나레이터",
    text: "심사 자료의 순서를 정하면 남은 변수가 줄어든다. 최종 결론은 규정 기반의 판단을 택한다.",
    next: "c4_resolution",
    evidence: "admin_ledgers",
  },

  c4_witness_prepare: {
    id: "c4_witness_prepare",
    backgroundKey: "witness_room",
    chapter: 4,
    scene: "witness",
    location: "심사 사전 준비실",
    speaker: "하린",
    text: "진술 기반은 공감 요소가 강하다. 그러나 숫자 없이 감정만으로 설득은 어렵다.",
    choices: [
      {
        choiceId: "c4_witness_trust_focus",
        label: "진술의 신뢰 지점을 우선적으로 부각한다",
        subtext: "불일치 지점을 최소한으로 압축",
        next: "c4_witness_trust_conclusion",
        effects: { empathy: 2 },
        evidence: "staff_interview",
        setFlags: { c4_witness_trust_focus: true },
      },
      {
        choiceId: "c4_witness_log_pair",
        label: "진술+로그를 병행해 상호보완 증거로 제시한다",
        subtext: "공감과 증거의 균형을 맞춤",
        next: "c4_witness_hybrid_conclusion",
        effects: { empathy: 1, insight: 1 },
        evidence: "internal_log",
        setFlags: { c4_witness_log_pair: true },
      },
    ],
  },
  c4_witness_trust_conclusion: {
    id: "c4_witness_trust_conclusion",
    chapter: 4,
    scene: "office",
    backgroundKey: "reconciliation_desk",
    location: "심사 사전 준비실",
    speaker: "하린",
    text: "진술의 반복 구간만 남기자 책임의 결이 부드러워진다. 심사자는 조작 여부보다 전달 누락의 피해를 먼저 보게 된다.",
    next: "c4_witness_conclusion",
    evidence: "staff_interview",
    document: true,
  },
  c4_witness_hybrid_conclusion: {
    id: "c4_witness_hybrid_conclusion",
    chapter: 4,
    scene: "office",
    backgroundKey: "witness_room",
    location: "심사 사전 준비실",
    speaker: "하치",
    text: "진술 옆에 로그를 붙이자 감정의 흔들림이 숫자로 고정된다. 반박은 줄었지만 결론의 온도도 조금 낮아졌다.",
    next: "c4_witness_conclusion",
    evidence: "internal_log",
    document: true,
  },
  c4_witness_conclusion: {
    id: "c4_witness_conclusion",
    backgroundKey: "witness_room",
    chapter: 4,
    scene: "office",
    location: "심사 사전 준비실",
    speaker: "하치",
    text: "진술이 증거와 만나면서 공백이 줄어들었다. 심사자는 결론 도출에 유리한 형태가 됐다.",
    next: "c4_resolution",
    document: true,
  },

  c4_press_plan: {
    id: "c4_press_plan",
    backgroundKey: "public_forum",
    chapter: 4,
    scene: "office",
    location: "심사 사전 준비실",
    speaker: "하린",
    text: "외부 보고 안으로 바꾼다면 사건의 본질보다 파급을 강조하게 된다. 리스크와 재발방지 항목을 먼저 제시한다.",
    choices: [
      {
        choiceId: "c4_press_reform_first",
        label: "재발방지 계획을 가장 먼저 제시한다",
        subtext: "심사 이후의 운영 안정성 확보",
        next: "c4_press_reform_review",
        effects: { order: 1, insight: 1 },
        evidence: "rule_note",
        setFlags: { c4_press_reform_first: true },
      },
      {
        choiceId: "c4_press_repair_first",
        label: "감정적 피해 완화 조항을 먼저 제시한다",
        subtext: "조직 신뢰 회복을 우선",
        next: "c4_press_repair_review",
        effects: { empathy: 1, order: -1 },
        evidence: "voice_name",
        setFlags: { c4_press_repair_first: true },
      },
    ],
  },
  c4_press_reform_review: {
    id: "c4_press_reform_review",
    chapter: 4,
    scene: "office",
    backgroundKey: "reform_blueprint",
    location: "심사 사전 준비실",
    speaker: "나레이터",
    text: "재발방지 계획이 먼저 올라가자 사건은 처벌보다 시스템 보수의 언어로 읽힌다. 위험도 표가 결론의 앞줄을 차지한다.",
    next: "c4_press_review",
    evidence: "rule_note",
    document: true,
  },
  c4_press_repair_review: {
    id: "c4_press_repair_review",
    chapter: 4,
    scene: "office",
    backgroundKey: "public_forum",
    location: "심사 사전 준비실",
    speaker: "하린",
    text: "피해 완화 조항을 앞세우자 회의록의 초점이 사람에게 옮겨간다. 대신 절차적 책임을 묻는 질문이 뒤따라 붙는다.",
    next: "c4_press_review",
    evidence: "voice_name",
    document: true,
  },
  c4_press_review: {
    id: "c4_press_review",
    backgroundKey: "public_forum",
    chapter: 4,
    scene: "office",
    location: "심사 사전 준비실",
    speaker: "나레이터",
    text: "둘 다 정합되어 보인다. 핵심은 최종 결론에서의 기준치 설정이다.",
    next: "c4_resolution",
    evidence: "double_id",
  },

  c4_resolution: {
    id: "c4_resolution",
    backgroundKey: "hearing_room",
    chapter: 4,
    scene: "office",
    location: "최종 심사 데스크",
    speaker: "나레이터",
    text: "최종 판정 단계다. 데이터의 무게감이 균형을 만들지, 감정이 무게를 이길지 선택은 네 손에 있다.",
    choices: [
      {
        choiceId: "c4_resolution_strict",
        label: "절차 위주의 엄격 보고로 결론을 마무리한다",
        subtext: "규칙 준수와 사후 점검 중심",
        next: "c5_assembly_open",
        effects: { order: 3 },
        evidence: "admin_ledgers",
        setFlags: { c4_resolution_strict: true },
      },
      {
        choiceId: "c4_resolution_repair",
        label: "동선 정리의 실마리를 먼저 요약해 완화안 제안",
        subtext: "관계 회복을 우선한 처리",
        next: "c5_public_floor",
        effects: { empathy: 2, order: -1 },
        evidence: "staff_interview",
        setFlags: { c4_resolution_repair: true },
      },
      {
        choiceId: "c4_resolution_balanced",
        label: "균형형 결론을 제출해 세 지표를 동시에 조정",
        subtext: "향후 재발방지와 회복 전략 병행",
        next: "c5_final_conference",
        effects: { insight: 2, empathy: 1, order: 1, bond: 1 },
        evidence: "rule_note",
        setFlags: { c4_resolution_balanced: true },
      },
    ],
  },

  c5_assembly_open: {
    id: "c5_assembly_open",
    chapter: 5,
    scene: "office",
    location: "최종 청문회 개회",
    speaker: "하린",
    text: "심사 절차가 시작됐다. 규정 중심 결론을 택하려면 증거의 논리 흐름과 질의 우선순위를 먼저 정리해야 한다.",
    next: "c5_draft_route",
    document: true,
  },
  c5_draft_route: {
    id: "c5_draft_route",
    chapter: 5,
    scene: "office",
    location: "최종 청문회 개회",
    speaker: "나레이터",
    text: "질문을 던지기 전에 결론 프레임을 고정해야 한다. 네가 선호하는 프레임을 고르면 후속 질문이 자동으로 정렬된다.",
    choices: [
      {
        choiceId: "c5_frame_evidence_chain",
        label: "증거 체인(카메라, 로그, 승인)을 중심으로 프레임 고정",
        subtext: "절차의 정합성 강화",
        next: "c5_evidence_bridge",
        effects: { insight: 1, order: 1 },
        evidence: "security_camera",
        setFlags: { c5_frame_evidence_chain: true },
      },
      {
        choiceId: "c5_frame_testimony_context",
        label: "증인 진술 우선 프레임으로 사람의 맥락을 부각",
        subtext: "피해와 동기 맥락의 신뢰도 강화",
        next: "c5_cross_exam",
        effects: { empathy: 2 },
        evidence: "staff_interview",
        setFlags: { c5_frame_testimony_context: true },
      },
      {
        choiceId: "c5_frame_public_balance",
        label: "정책/규정 프레임을 병행해 균형 질문 설계",
        subtext: "예외 조항과 재발방지안을 같이 제시",
        next: "c5_public_plan",
        effects: { empathy: 1, order: 1, insight: 1 },
        evidence: "rule_note",
        setFlags: { c5_frame_public_balance: true },
      },
    ],
  },
  c5_evidence_bridge: {
    id: "c5_evidence_bridge",
    backgroundKey: "cctv_room",
    chapter: 5,
    scene: "office",
    location: "최종 청문회 개회",
    speaker: "해치",
    text: "보안·출입·승인 로그를 한 줄로 묶어 질문 순서를 정리했다. 심사위원은 처음부터 수치로 움직인다.",
    next: "c5_evidence_bridge_followup",
    evidence: "security_camera",
  },
  c5_cross_exam: {
    id: "c5_cross_exam",
    backgroundKey: "witness_room",
    chapter: 5,
    scene: "office",
    location: "최종 청문회 개회",
    speaker: "하린",
    text: "진술의 긴장 구간을 먼저 떼어내야 한다. 상충되는 표현을 짧게 분해해 반복 질문으로 정리한다.",
    next: "c5_cross_exam_followup",
    evidence: "internal_log",
  },
  c5_public_plan: {
    id: "c5_public_plan",
    backgroundKey: "public_forum",
    chapter: 5,
    scene: "office",
    location: "최종 청문회 개회",
    speaker: "나레이터",
    text: "사람과 규정의 틀을 함께 세우면 신뢰도는 올라가고 저항은 늦게 생긴다. 발표자료를 재구성해 다음 단계로 넘긴다.",
    next: "c5_public_plan_followup",
    document: true,
  },
  c5_evidence_bridge_followup: {
    id: "c5_evidence_bridge_followup",
    backgroundKey: "cctv_room",
    chapter: 5,
    scene: "office",
    location: "증거 체인 고정석",
    speaker: "하린",
    text: "카메라, 로그, 승인 순서가 질문지 상단에 고정된다. 이 경로는 이후 패널 심의에서도 사람의 설명보다 확인 가능한 체인을 먼저 보게 만든다.",
    next: "c5_panel_plan",
    document: true,
  },
  c5_cross_exam_followup: {
    id: "c5_cross_exam_followup",
    backgroundKey: "witness_room",
    chapter: 5,
    scene: "office",
    location: "증언 맥락 고정석",
    speaker: "해치",
    text: "질문지는 증언의 긴장 구간을 먼저 펼친다. 이 경로는 이후 패널 심의에서도 누가 틀렸는지보다 왜 설명이 어긋났는지를 먼저 묻게 만든다.",
    next: "c5_panel_plan",
    document: true,
  },
  c5_public_plan_followup: {
    id: "c5_public_plan_followup",
    backgroundKey: "public_forum",
    chapter: 5,
    scene: "office",
    location: "공개 균형 고정석",
    speaker: "나레이터",
    text: "질문지는 공개 범위와 제도 개선 메모를 함께 남긴다. 이 경로는 이후 패널 심의에서도 단일 책임보다 설명 가능한 균형안을 먼저 요구하게 만든다.",
    next: "c5_panel_plan",
    document: true,
  },
  c5_panel_plan: {
    id: "c5_panel_plan",
    chapter: 5,
    scene: "office",
    backgroundKey: "public_forum",
    location: "최종 심의 룸",
    speaker: "하치",
    text: "패널이 첫 질문을 끝내자 네게 추가 증거를 요청한다. 공개 범위를 정하지 않으면 반박이 길어진다.",
    choices: [
      {
        choiceId: "c5_panel_censure",
        label: "규정 조문으로 반박하고 즉시 결론을 유도",
        subtext: "심사 시간을 단축",
        next: "c5_resolution_censure",
        effects: { order: 2 },
        setFlags: { panel_censure: true },
      },
      {
        choiceId: "c5_panel_reconciliation",
        label: "정서적 맥락을 짚어 완화 조항으로 신뢰 확보",
        subtext: "관계 회복의 비용을 줄임",
        next: "c5_resolution_reconciliation",
        effects: { empathy: 2, bond: 1 },
        evidence: "voice_name",
        setFlags: { panel_reconciliation: true },
      },
      {
        choiceId: "c5_panel_reform",
        label: "두 축을 묶어 실행 지침과 함께 동시 보고",
        subtext: "재발방지까지 포함한 정합 결론",
        next: "c5_resolution_reform",
        effects: { insight: 1, order: 1, empathy: 1 },
        evidence: "admin_ledgers",
        setFlags: { panel_reform: true },
      },
    ],
  },
  c5_resolution_censure: {
    id: "c5_resolution_censure",
    chapter: 5,
    scene: "censure",
    backgroundKey: "censure_chamber",
    location: "최종 심의 룸",
    speaker: "하린",
    text: "규정 조문을 전면에 세우자 패널의 질문은 빠르게 좁혀졌다. 대신 당사자 설명은 공식 기록의 부속 의견으로 밀려난다.",
    next: "c5_resolution_censure_followup",
    setFlags: { panel_censure: true },
    document: true,
  },
  c5_resolution_reconciliation: {
    id: "c5_resolution_reconciliation",
    chapter: 5,
    scene: "reconciliation",
    backgroundKey: "reconciliation_desk",
    location: "증언 조정실",
    speaker: "해치",
    text: "완화 조항을 먼저 설명하자 증언자들이 다시 말을 이어갔다. 판정은 늦어졌지만, 서로 다른 기억을 한 문장 안에 묶을 여지가 생겼다.",
    next: "c5_resolution_reconciliation_followup",
    setFlags: { panel_reconciliation: true },
    evidence: "staff_interview",
  },
  c5_resolution_reform: {
    id: "c5_resolution_reform",
    chapter: 5,
    scene: "reform",
    backgroundKey: "reform_blueprint",
    location: "개선 설계 보드",
    speaker: "나레이터",
    text: "조문과 맥락을 함께 올리자 패널은 결론보다 다음 운영 지침을 먼저 물었다. 사건 처리는 재발방지 설계로 이어진다.",
    next: "c5_resolution_reform_followup",
    setFlags: { panel_reform: true },
    document: true,
  },
  c5_resolution_censure_followup: {
    id: "c5_resolution_censure_followup",
    chapter: 5,
    scene: "office",
    backgroundKey: "censure_chamber",
    location: "책임 범위 고정석",
    speaker: "하린",
    text: "패널은 결론 전에 책임 범위 표를 먼저 잠근다. 이 선택은 이후 공개 방식에서도 관계 회복보다 공식 기록의 흔들림을 줄이는 쪽으로 압력을 남긴다.",
    next: "c5_resolution_summary",
    document: true,
  },
  c5_resolution_reconciliation_followup: {
    id: "c5_resolution_reconciliation_followup",
    chapter: 5,
    scene: "village",
    backgroundKey: "reconciliation_desk",
    location: "회복 문장 조정석",
    speaker: "해치",
    text: "패널은 결론 전에 유감 표명 문장을 먼저 다듬는다. 이 선택은 이후 공개 방식에서도 책임 확정보다 조직 신뢰를 회복하는 쪽으로 압력을 남긴다.",
    next: "c5_resolution_summary",
    document: true,
  },
  c5_resolution_reform_followup: {
    id: "c5_resolution_reform_followup",
    chapter: 5,
    scene: "maze",
    backgroundKey: "reform_blueprint",
    location: "개선 지표 고정석",
    speaker: "나레이터",
    text: "패널은 결론 전에 다음 운영 지표를 먼저 고정한다. 이 선택은 이후 공개 방식에서도 단기 판정보다 재발방지 기준을 남기는 쪽으로 압력을 남긴다.",
    next: "c5_resolution_summary",
    document: true,
  },
  c5_resolution_summary: {
    id: "c5_resolution_summary",
    chapter: 5,
    scene: "office",
    backgroundKey: "hearing_room",
    location: "최종 심의 룸",
    speaker: "나레이터",
    text: "최종 보고는 지금 확정할 수 있다. 내부 공지, 공개 조치, 후속 지표를 어떻게 조합해 판정을 남길지 고르자.",
    choices: [
      {
        choiceId: "c5_summary_internal_notice",
        label: "내부 공지로만 결론 확정",
        subtext: "신속한 처리와 통제 확보",
        next: "c5_internal_notice",
        effects: { order: 2 },
        evidence: "admin_ledgers",
        setFlags: { summary_internal_notice: true },
      },
      {
        choiceId: "c5_summary_public_trust",
        label: "대외 공개 범위를 함께 제시해 신뢰 회복",
        subtext: "조직 신뢰도를 높이는 선택",
        next: "c5_public_trust",
        effects: { empathy: 2, insight: 1 },
        evidence: "staff_interview",
        setFlags: { summary_public_trust: true },
      },
      {
        choiceId: "c5_summary_followup_schedule",
        label: "균형형 결론문을 남기고 추적 일정까지 동봉",
        subtext: "장기 재발방지 중심 결론",
        next: "c5_followup_schedule",
        effects: { insight: 2, empathy: 1, order: 1, bond: 1 },
        evidence: "rule_note",
        setFlags: { summary_followup_schedule: true },
      },
    ],
    document: true,
  },
  c5_internal_notice: {
    id: "c5_internal_notice",
    chapter: 5,
    scene: "office",
    backgroundKey: "censure_chamber",
    location: "내부 공지 검토실",
    speaker: "하린",
    text: "내부 공지는 판정의 경계를 선명하게 남긴다. 관련 부서에는 책임 범위와 보존해야 할 로그를 먼저 전달하고, 공개 설명은 예비 심의에서 다시 조율하기로 한다.",
    next: "mid_route_gate",
    setFlags: { summary_internal_notice: true },
    evidence: "admin_ledgers",
    document: true,
  },
  c5_public_trust: {
    id: "c5_public_trust",
    chapter: 5,
    scene: "office",
    backgroundKey: "public_forum",
    location: "공개 신뢰 브리핑 룸",
    speaker: "해치",
    text: "대외 공개안은 결론보다 신뢰 회복의 순서를 먼저 묻는다. 확인된 사실, 아직 말할 수 없는 범위, 추가 설명 시점을 분리해 오해가 번지지 않게 묶는다.",
    next: "mid_route_gate",
    setFlags: { summary_public_trust: true },
    evidence: "staff_interview",
    document: true,
  },
  c5_followup_schedule: {
    id: "c5_followup_schedule",
    chapter: 5,
    scene: "maze",
    backgroundKey: "reform_blueprint",
    location: "추적 일정 보드",
    speaker: "나레이터",
    text: "균형형 결론문에는 후속 점검 일정이 함께 붙었다. 재검토 날짜, 담당 기록, 공개 가능한 개선 지표를 남겨 이번 판정이 다음 사건의 기준으로 이어지게 한다.",
    next: "mid_route_gate",
    setFlags: { summary_followup_schedule: true },
    evidence: "rule_note",
    document: true,
  },
  c5_public_floor: {
    id: "c5_public_floor",
    chapter: 5,
    scene: "office",
    location: "공개 브리핑 룸",
    speaker: "하린",
    text: "완화안을 먼저 전달하면 반발은 줄지만, 기록의 완전성은 반드시 체크해야 한다. 공개 가능한 범위를 선별한다.",
    next: "c5_panel_plan",
    evidence: "double_id",
  },
  c5_final_conference: {
    id: "c5_final_conference",
    chapter: 5,
    scene: "office",
    location: "공개 브리핑 룸",
    speaker: "해치",
    text: "균형안을 선택하면, 누구도 완전히 만족하지 못하더라도 분쟁 에너지를 줄이는 방식으로 기록할 수 있다. 마지막 정합만 남았다.",
    next: "c5_resolution_summary",
  },
  c6_review_order_entry: {
    id: "c6_review_order_entry",
    chapter: 6,
    scene: "office",
    backgroundKey: "censure_chamber",
    location: "절차 우선 예비 브리핑",
    speaker: "하린",
    text: "누적된 선택은 내부 공지와 책임 범위를 먼저 닫는 방향으로 모였다. 예비회의는 회복보다 기록 보존, 공개보다 절차 기준을 먼저 확인하며 열린다.",
    next: "c6_review_order_followup",
    document: true,
  },
  c6_review_human_entry: {
    id: "c6_review_human_entry",
    chapter: 6,
    scene: "office",
    backgroundKey: "reconciliation_desk",
    location: "신뢰 회복 예비 브리핑",
    speaker: "해치",
    text: "누적된 선택은 신뢰 회복과 설명 순서를 먼저 묶는 방향으로 모였다. 예비회의는 결론의 단단함보다 오해가 번지지 않는 공개 범위를 먼저 점검한다.",
    next: "c6_review_human_followup",
    document: true,
  },
  c6_review_balanced_entry: {
    id: "c6_review_balanced_entry",
    chapter: 6,
    scene: "office",
    backgroundKey: "reform_blueprint",
    location: "후속 지표 예비 브리핑",
    speaker: "나레이터",
    text: "누적된 선택은 책임, 회복, 재발방지를 함께 남기는 방향으로 모였다. 예비회의는 판정문보다 다음 사건에서 재사용할 기준표를 먼저 펼친다.",
    next: "c6_review_balanced_followup",
    document: true,
  },
  c6_review_mixed_entry: {
    id: "c6_review_mixed_entry",
    chapter: 6,
    scene: "office",
    backgroundKey: "evidence_board",
    location: "혼합 쟁점 예비 브리핑",
    speaker: "나레이터",
    text: "누적된 선택은 하나의 검토 축으로 모이지 않았다. 예비회의는 책임, 회복, 재발방지 중 무엇을 먼저 말할지 확정하지 않고 충돌 쟁점을 먼저 테이블에 올린다.",
    next: "c6_review_mixed_followup",
    document: true,
  },
  c6_review_order_followup: {
    id: "c6_review_order_followup",
    chapter: 6,
    scene: "office",
    backgroundKey: "censure_chamber",
    location: "절차 검토 체크리스트",
    speaker: "하린",
    text: "검토 테이블은 책임 범위와 통보 기준을 먼저 고정한다. 다음 회의로 넘어가기 전, 지금까지의 선택이 공개 순서보다 증거 보존을 앞세웠다는 점을 사건 기록에 남긴다.",
    next: "c6_review_open",
    document: true,
  },
  c6_review_human_followup: {
    id: "c6_review_human_followup",
    chapter: 6,
    scene: "office",
    backgroundKey: "reconciliation_desk",
    location: "회복 검토 체크리스트",
    speaker: "해치",
    text: "검토 테이블은 진술 보호와 설명 범위를 먼저 고정한다. 다음 회의로 넘어가기 전, 지금까지의 선택이 단정적 공지보다 관계 회복을 앞세웠다는 점을 사건 기록에 남긴다.",
    next: "c6_review_open",
    document: true,
  },
  c6_review_balanced_followup: {
    id: "c6_review_balanced_followup",
    chapter: 6,
    scene: "office",
    backgroundKey: "reform_blueprint",
    location: "후속 지표 체크리스트",
    speaker: "나레이터",
    text: "검토 테이블은 책임, 회복, 재발방지 지표를 함께 고정한다. 다음 회의로 넘어가기 전, 지금까지의 선택이 단일 판정보다 재사용 가능한 기준을 앞세웠다는 점을 사건 기록에 남긴다.",
    next: "c6_review_open",
    document: true,
  },
  c6_review_mixed_followup: {
    id: "c6_review_mixed_followup",
    chapter: 6,
    scene: "office",
    backgroundKey: "evidence_board",
    location: "혼합 쟁점 체크리스트",
    speaker: "하린",
    text: "검토 테이블은 상충하는 선택의 흔적을 지우지 않는다. 다음 회의로 넘어가기 전, 어느 기준도 단독 우세가 아니었다는 점을 별도 쟁점으로 남긴다.",
    next: "c6_review_open",
    document: true,
  },
  c6_review_open: {
    id: "c6_review_open",
    chapter: 6,
    scene: "office",
    backgroundKey: "evidence_board",
    location: "심의 예비 회의실",
    speaker: "해치",
    text: "최종 심의 직전, 결함 지점은 이미 정리되었어야 한다는 원칙이 있다. 지금부터는 공백을 메우는 단계다.",
    next: "c6_data_review",
  },
  c6_data_review: {
    id: "c6_data_review",
    chapter: 6,
    scene: "office",
    location: "심의 예비 회의실",
    speaker: "하린",
    text: "로그를 다시 보면 증거의 빈 칸이 분명해. 같은 사람의 동선이 규정상 한 번밖에 안 떠야 하는데, 두 번 표시돼.",
    choices: [
      {
        choiceId: "c6_data_record_chain",
        label: "이중 기록이 맞는지 타임스탬프부터 검토",
        subtext: "근거 우선의 기본 경로",
        next: "c6_record_chain",
        effects: { insight: 1, order: 1 },
        setFlags: { prebrief_record_chain: true },
      },
      {
        choiceId: "c6_data_witness_circle",
        label: "목격자 진술을 추가로 교차 검증",
        subtext: "현장 맥락을 먼저 확인",
        next: "c6_witness_circle",
        effects: { empathy: 2 },
        setFlags: { prebrief_witness_circle: true },
      },
      {
        choiceId: "c6_data_rule_review",
        label: "규정 조항대로 예외 요건을 점검",
        subtext: "예외 적용 범위를 분명히",
        next: "c6_legal_consult",
        effects: { order: 1 },
        evidence: "rule_note",
        setFlags: { prebrief_rule_review: true },
      },
    ],
  },
  c6_record_chain: {
    id: "c6_record_chain",
    chapter: 6,
    scene: "office",
    backgroundKey: "server_room",
    location: "심의 예비 회의실",
    speaker: "하린",
    text: "기록체인을 되짚으면 결합 지점이 선명해진다. 이중 ID 의심 항목을 기준으로 근거를 한 줄로 정리해.",
    next: "c6_record_chain_prebrief",
    evidence: "double_id",
  },
  c6_record_chain_prebrief: {
    id: "c6_record_chain_prebrief",
    chapter: 6,
    scene: "office",
    backgroundKey: "server_room",
    location: "증거 보드 검토실",
    speaker: "해치",
    text: "이중 ID 경로는 별도 브리핑 흔적을 남긴다. 증언보다 기록체인을 먼저 세우고, 공개 자료는 검증 가능한 타임스탬프 순서로 재정렬한다.",
    next: "c6_boarding_call",
    setFlags: { prebrief_record_chain: true },
    evidence: "internal_log",
    document: true,
  },
  c6_witness_circle: {
    id: "c6_witness_circle",
    chapter: 6,
    scene: "office",
    backgroundKey: "witness_room",
    location: "심의 예비 회의실",
    speaker: "해치",
    text: "목격자 그룹을 한 명씩 돌려보면 같은 장면을 서로 다르게 본 이유가 보일 때가 있다. 기억은 정렬되지 않으면 반론이 생긴다.",
    next: "c6_witness_circle_prebrief",
    evidence: "staff_interview",
  },
  c6_witness_circle_prebrief: {
    id: "c6_witness_circle_prebrief",
    chapter: 6,
    scene: "office",
    backgroundKey: "reconciliation_desk",
    location: "증언 조정 데스크",
    speaker: "하린",
    text: "증언 우선 경로는 부드러운 사전 브리핑을 만든다. 서로 어긋난 기억은 차이가 난 이유별로 묶이고, 다음 공개 대응은 신뢰를 보호하면서도 질문을 좁힐 수 있다.",
    next: "c6_boarding_call",
    setFlags: { prebrief_witness_circle: true },
    evidence: "voice_name",
  },
  c6_legal_consult: {
    id: "c6_legal_consult",
    chapter: 6,
    scene: "office",
    backgroundKey: "rule_archive",
    location: "심의 예비 회의실",
    speaker: "나레이터",
    text: "법규는 단단한 철벽이 아니라, 적용 조건이 있는 프레임이다. 조건이 맞지 않으면 공정성이 먼저 무너진다.",
    next: "c6_legal_consult_prebrief",
    document: true,
    evidence: "rule_note",
  },
  c6_legal_consult_prebrief: {
    id: "c6_legal_consult_prebrief",
    chapter: 6,
    scene: "office",
    backgroundKey: "rule_archive",
    location: "규정 검토 테이블",
    speaker: "해치",
    text: "규정 우선 경로는 예외 범위와 입증 책임을 중심으로 공개 대응을 좁힌다. 보고서는 왜 절차적 답변이 공개 반박보다 먼저 와야 하는지 설명한다.",
    next: "c6_boarding_call",
    setFlags: { prebrief_rule_review: true },
    evidence: "rule_note",
    document: true,
  },
  c6_boarding_call: {
    id: "c6_boarding_call",
    chapter: 6,
    scene: "office",
    backgroundKey: "public_forum",
    location: "심의 예비 회의실",
    speaker: "해치",
    text: "다음 단계는 대외 커뮤니케이션이다. 공개 범위를 정하지 않으면 루머가 먼저 채널을 선점한다.",
    choices: [
      {
        choiceId: "c6_call_media_strategy",
        label: "대외 브리핑은 기록 검증 순으로 진행",
        subtext: "1차 안정화는 정확성 우선",
        next: "c6_media_strategy",
        effects: { order: 1 },
        setFlags: { rumor_media_strategy: true },
      },
      {
        choiceId: "c6_call_public_forum",
        label: "공개 포럼에서 이해관계자 질문 수렴",
        subtext: "현장 신뢰를 먼저 회복",
        next: "c6_public_forum",
        effects: { empathy: 1 },
        setFlags: { rumor_public_forum: true },
      },
      {
        choiceId: "c6_call_internal_discipline",
        label: "내부 점검팀에 긴급 점검 지시",
        subtext: "근본 원인 추적을 강화",
        next: "c6_internal_discipline",
        effects: { insight: 1 },
        setFlags: { rumor_internal_discipline: true },
      },
    ],
  },
  c6_media_strategy: {
    id: "c6_media_strategy",
    chapter: 6,
    scene: "press",
    backgroundKey: "public_forum",
    location: "대외 브리핑 준비실",
    speaker: "하린",
    text: "대외 발표문은 확신의 문장이 아니라 통제의 문장이다. 공개 범위를 단계로 나눠 제시하면 불안은 완화된다.",
    next: "c6_rumor_control",
    setFlags: { rumor_media_strategy: true },
  },
  c6_public_forum: {
    id: "c6_public_forum",
    chapter: 6,
    scene: "office",
    backgroundKey: "public_forum",
    location: "열린 토론 라운드",
    speaker: "해치",
    text: "의견을 묶어 묻고, 선명한 응답만 남겨야 한다. 불확실한 문항을 먼저 걸러야 공론장이 흔들리지 않는다.",
    next: "c6_forum_rumor_control",
    setFlags: { rumor_public_forum: true },
    evidence: "staff_interview",
  },
  c6_internal_discipline: {
    id: "c6_internal_discipline",
    chapter: 6,
    scene: "office",
    backgroundKey: "censure_chamber",
    location: "내부 통제 점검 라운드",
    speaker: "나레이터",
    text: "내부 징후를 먼저 닫고 시작하는 방식은 위험하다. 왜곡 포인트가 반복된다면 문서를 거꾸로 추적해야 한다.",
    next: "c6_discipline_rumor_control",
    setFlags: { rumor_internal_discipline: true },
    evidence: "admin_ledgers",
  },
  c6_rumor_control: {
    id: "c6_rumor_control",
    chapter: 6,
    scene: "office",
    backgroundKey: "evidence_board",
    location: "심의 예비 회의실",
    speaker: "해치",
    text: "커뮤니케이션은 사실과 톤을 분리해야 한다. 과장은 줄이고, 공식 채널은 한 번에 정리한다.",
    next: "route_bridge",
    evidence: "double_id",
    document: true,
  },
  c6_forum_rumor_control: {
    id: "c6_forum_rumor_control",
    chapter: 6,
    scene: "office",
    backgroundKey: "public_forum",
    location: "공개 질문 라운지",
    speaker: "하린",
    text: "공개 포럼 경로는 공식 발표 전에 이해관계자 질문을 먼저 모은다. 팀은 증언 묶음이 뒷받침할 수 있는 내용만 답하고, 다툼이 있는 항목은 보류 상태로 남긴다.",
    next: "route_bridge",
    setFlags: { rumor_public_forum: true },
    evidence: "staff_interview",
    document: true,
  },
  c6_discipline_rumor_control: {
    id: "c6_discipline_rumor_control",
    chapter: 6,
    scene: "office",
    backgroundKey: "censure_chamber",
    location: "내부 점검 라운지",
    speaker: "해치",
    text: "내부 점검 경로는 공개 발언 전에 접근 이력을 먼저 잠근다. 루머 대응은 의심 관리자 경로를 분리하고, 장부를 보존하며, 넓은 주장 발표를 늦추는 통제 계획이 된다.",
    next: "route_bridge",
    setFlags: { rumor_internal_discipline: true },
    evidence: "admin_ledgers",
    document: true,
  },
  c7_bridge_order: {
    id: "c7_bridge_order",
    chapter: 7,
    scene: "office",
    backgroundKey: "censure_chamber",
    location: "절차 심문 회랑",
    speaker: "해치",
    text: "지금까지의 선택은 절차의 순서를 먼저 세웠다. 최종 청문은 책임 주체, 증거 순서, 통보 기준을 한 줄로 묶어 확인하는 방식으로 열린다.",
    next: "c7_bridge_order_followup",
    document: true,
  },
  c7_bridge_human: {
    id: "c7_bridge_human",
    chapter: 7,
    scene: "office",
    backgroundKey: "witness_room",
    location: "증언 조정 회랑",
    speaker: "하린",
    text: "지금까지의 선택은 사람의 진술과 회복 가능성을 남겼다. 최종 청문은 피해와 오해를 어떻게 정정할지 먼저 묻는 방식으로 열린다.",
    next: "c7_bridge_human_followup",
    document: true,
  },
  c7_bridge_balanced: {
    id: "c7_bridge_balanced",
    chapter: 7,
    scene: "maze",
    backgroundKey: "reform_blueprint",
    location: "재발방지 설계 회랑",
    speaker: "나레이터",
    text: "지금까지의 선택은 기록, 진술, 제도 개선을 한 장의 설계도로 묶었다. 최종 청문은 판정과 다음 기준을 동시에 다루는 방식으로 열린다.",
    next: "c7_bridge_balanced_followup",
    document: true,
  },
  c7_bridge_mixed: {
    id: "c7_bridge_mixed",
    chapter: 7,
    scene: "office",
    backgroundKey: "panel_room",
    location: "혼합 쟁점 회랑",
    speaker: "해치",
    text: "지금까지의 선택은 최종 청문을 한 방향으로 밀지 않는다. 심문은 책임, 회복, 제도 개선 중 어느 질문부터 열어야 하는지 자체를 먼저 묻는 방식으로 시작된다.",
    next: "c7_bridge_mixed_followup",
    document: true,
  },
  c7_bridge_order_followup: {
    id: "c7_bridge_order_followup",
    chapter: 7,
    scene: "office",
    backgroundKey: "censure_chamber",
    location: "절차 최종 점검석",
    speaker: "하린",
    text: "최종 청문 전 마지막 점검은 책임 주체와 기록 보존 순서를 다시 확인한다. 플레이어의 누적 선택은 심문 질문의 첫 줄을 절차와 책임으로 바꿔 놓았다.",
    next: "c7_prehearing",
    document: true,
  },
  c7_bridge_human_followup: {
    id: "c7_bridge_human_followup",
    chapter: 7,
    scene: "office",
    backgroundKey: "witness_room",
    location: "증언 최종 점검석",
    speaker: "해치",
    text: "최종 청문 전 마지막 점검은 피해 설명과 오해 정정 순서를 다시 확인한다. 플레이어의 누적 선택은 심문 질문의 첫 줄을 사람의 회복 가능성으로 바꿔 놓았다.",
    next: "c7_prehearing",
    document: true,
  },
  c7_bridge_balanced_followup: {
    id: "c7_bridge_balanced_followup",
    chapter: 7,
    scene: "maze",
    backgroundKey: "reform_blueprint",
    location: "개선안 최종 점검석",
    speaker: "나레이터",
    text: "최종 청문 전 마지막 점검은 판정문과 재발방지 기준을 동시에 확인한다. 플레이어의 누적 선택은 심문 질문의 첫 줄을 다음 사건에서 재사용할 구조로 바꿔 놓았다.",
    next: "c7_prehearing",
    document: true,
  },
  c7_bridge_mixed_followup: {
    id: "c7_bridge_mixed_followup",
    chapter: 7,
    scene: "office",
    backgroundKey: "panel_room",
    location: "혼합 쟁점 최종 점검석",
    speaker: "나레이터",
    text: "최종 청문 전 마지막 점검은 결론의 방향보다 쟁점 배열을 먼저 정한다. 플레이어의 누적 선택은 심문 질문의 첫 줄을 단일 판정가 아닌 비교 질문으로 바꿔 놓았다.",
    next: "c7_prehearing",
    document: true,
  },
  c7_prehearing: {
    id: "c7_prehearing",
    chapter: 7,
    scene: "panel",
    backgroundKey: "panel_room",
    location: "최종 청문 회의실",
    speaker: "하린",
    text: "심의전 브리핑이 끝났다. 최종 결론은 한 문장으로 압축될 수 없어; 증거와 사유를 정렬해 순서를 잡자.",
    next: "c7_panel_assembly",
  },
  c7_panel_assembly: {
    id: "c7_panel_assembly",
    chapter: 7,
    scene: "office",
    location: "최종 청문 회의실",
    speaker: "해치",
    text: "패널의 첫 질문은 사실보다 구조를 본다. 핵심이 어디에 묶였는지 한 번 더 보여주자.",
    choices: [
      {
        choiceId: "c7_panel_core_testimony",
        label: "핵심 근거 먼저 제시하고 순서 정리",
        subtext: "판단을 위한 최소 증거 제공",
        next: "c7_core_testimony",
        effects: { empathy: 2 },
        setFlags: { c7_panel_core_testimony: true },
      },
      {
        choiceId: "c7_panel_audit_record",
        label: "감사 기록을 항목별로 재진술",
        subtext: "오해의 여지를 줄임",
        next: "c7_audit_statement",
        effects: { order: 1 },
        setFlags: { c7_panel_audit_record: true },
      },
      {
        choiceId: "c7_panel_expert_reform",
        label: "전문가 의견을 연결해 제안 마무리",
        subtext: "재발 방지까지 보여줌",
        next: "c7_expert_input",
        effects: { insight: 1 },
        evidence: "five_links",
        setFlags: { c7_panel_expert_reform: true },
      },
    ],
  },
  c7_core_testimony: {
    id: "c7_core_testimony",
    chapter: 7,
    scene: "office",
    backgroundKey: "witness_room",
    location: "최종 청문 회의실",
    speaker: "하린",
    text: "핵심 증언은 단어보다 맥락을 먼저 읽어야 한다. 모순이 보여도, 연결 구조가 맞으면 한 번 더 설득된다.",
    next: "c7_core_testimony_followup",
  },
  c7_audit_statement: {
    id: "c7_audit_statement",
    backgroundKey: "hearing_room",
    chapter: 7,
    scene: "office",
    location: "최종 청문 회의실",
    speaker: "나레이터",
    text: "감사관 진술은 간결해야 한다. 결론보다 증거의 흐름을 먼저 보여주면 심의의 반박 시간이 줄어든다.",
    next: "c7_audit_statement_followup",
    evidence: "admin_ledgers",
  },
  c7_expert_input: {
    id: "c7_expert_input",
    chapter: 7,
    scene: "office",
    backgroundKey: "reform_blueprint",
    location: "최종 청문 회의실",
    speaker: "해치",
    text: "전문가 코멘트를 뒤로 빼두면 마지막 단계에서 약점이 생긴다. 현재까지의 근거와 연결된 제안을 붙여야 한다.",
    next: "c7_expert_input_followup",
    evidence: "voice_name",
  },
  c7_core_testimony_followup: {
    id: "c7_core_testimony_followup",
    chapter: 7,
    scene: "office",
    backgroundKey: "witness_room",
    location: "핵심 증언 고정석",
    speaker: "해치",
    text: "패널의 질문지는 증언 맥락을 첫 줄에 남긴다. 이후 교차 질문도 처벌 가능성보다 피해 설명과 회복 가능성을 먼저 확인하게 된다.",
    next: "c7_cross_question",
    document: true,
  },
  c7_audit_statement_followup: {
    id: "c7_audit_statement_followup",
    backgroundKey: "hearing_room",
    chapter: 7,
    scene: "office",
    location: "감사 기록 고정석",
    speaker: "하린",
    text: "패널의 질문지는 감사 기록과 반박 순서를 첫 줄에 남긴다. 이후 교차 질문도 누가 무엇을 입증해야 하는지를 먼저 확인하게 된다.",
    next: "c7_cross_question",
    document: true,
  },
  c7_expert_input_followup: {
    id: "c7_expert_input_followup",
    chapter: 7,
    scene: "office",
    backgroundKey: "reform_blueprint",
    location: "전문가 권고 고정석",
    speaker: "나레이터",
    text: "패널의 질문지는 전문가 권고와 재발방지 항목을 첫 줄에 남긴다. 이후 교차 질문도 이번 판정이 다음 사건의 기준이 될 수 있는지를 먼저 확인하게 된다.",
    next: "c7_cross_question",
    document: true,
  },
  c7_cross_question: {
    id: "c7_cross_question",
    chapter: 7,
    scene: "office",
    location: "최종 청문 회의실",
    speaker: "나레이터",
    text: "교차 질문이 시작됐다. 여기서 누가 무엇을 먼저 증명하는지에 따라 판정 톤이 바뀐다.",
    choices: [
      {
        choiceId: "c7_cross_procedure",
        label: "절차 준수와 기록 정합성을 우선",
        subtext: "신뢰 가능한 기준 제시",
        next: "c7_cross_procedure_answer",
        effects: { order: 1 },
        evidence: "admin_ledgers",
        setFlags: { c7_cross_procedure_answer: true },
      },
      {
        choiceId: "c7_cross_recovery",
        label: "공감적 정정 조항으로 신뢰 회복",
        subtext: "피해자 보호와 관계 회복 동시",
        next: "c7_cross_recovery_answer",
        effects: { empathy: 2 },
        evidence: "voice_name",
        setFlags: { c7_cross_recovery_answer: true },
      },
      {
        choiceId: "c7_cross_summary",
        label: "근거를 결론 문장으로 한 번에 요약",
        subtext: "의사결정자의 피로 감소",
        next: "c7_cross_summary_answer",
        effects: { insight: 1, bond: 1 },
        evidence: "five_links",
        setFlags: { c7_cross_summary_answer: true },
      },
    ],
  },
  c7_cross_procedure_answer: {
    id: "c7_cross_procedure_answer",
    chapter: 7,
    scene: "office",
    backgroundKey: "hearing_room",
    location: "최종 청문 회의실",
    speaker: "하린",
    text: "하린은 교차 질문을 절차의 순서로 되돌렸다. 접수, 검토, 대조, 통보가 같은 기준으로 이어졌다는 점을 짚자 패널의 표정이 먼저 안정됐다.",
    next: "c7_cross_procedure_followup",
    evidence: "admin_ledgers",
    setFlags: { c7_cross_procedure_answer: true },
  },
  c7_cross_recovery_answer: {
    id: "c7_cross_recovery_answer",
    chapter: 7,
    scene: "office",
    backgroundKey: "reconciliation_desk",
    location: "최종 청문 회의실",
    speaker: "해치",
    text: "해치는 정정 조항을 처벌의 반대말로 설명하지 않았다. 피해자가 다시 기록을 믿을 수 있게 만드는 회복 절차라고 못박았다.",
    next: "c7_cross_recovery_followup",
    evidence: "voice_name",
    setFlags: { c7_cross_recovery_answer: true },
  },
  c7_cross_summary_answer: {
    id: "c7_cross_summary_answer",
    chapter: 7,
    scene: "office",
    backgroundKey: "panel_room",
    location: "최종 청문 회의실",
    speaker: "나레이터",
    text: "근거는 길게 늘어놓지 않았다. 다섯 연결점과 감사 기록, 증언의 방향을 한 문장으로 묶자 결론의 기준선이 분명해졌다.",
    next: "c7_cross_summary_followup",
    evidence: "five_links",
    setFlags: { c7_cross_summary_answer: true },
  },
  c7_cross_procedure_followup: {
    id: "c7_cross_procedure_followup",
    chapter: 7,
    scene: "office",
    backgroundKey: "hearing_room",
    location: "절차 답변 고정석",
    speaker: "하린",
    text: "절차 답변은 최종 결론지의 첫 번째 검토란에 남는다. 이제 마지막 선택은 책임 범위를 어떻게 닫을지에 더 강하게 묶인다.",
    next: "c7_final_resolution",
    document: true,
  },
  c7_cross_recovery_followup: {
    id: "c7_cross_recovery_followup",
    chapter: 7,
    scene: "office",
    backgroundKey: "reconciliation_desk",
    location: "회복 답변 고정석",
    speaker: "해치",
    text: "회복 답변은 최종 결론지의 두 번째 검토란에 남는다. 이제 마지막 선택은 정정과 유감 표명을 어떻게 닫을지에 더 강하게 묶인다.",
    next: "c7_final_resolution",
    document: true,
  },
  c7_cross_summary_followup: {
    id: "c7_cross_summary_followup",
    chapter: 7,
    scene: "office",
    backgroundKey: "panel_room",
    location: "요약 답변 고정석",
    speaker: "나레이터",
    text: "요약 답변은 최종 결론지의 세 번째 검토란에 남는다. 이제 마지막 선택은 근거와 재발방지 기준을 한 문장으로 닫을지에 더 강하게 묶인다.",
    next: "c7_final_resolution",
    document: true,
  },
  c7_final_resolution: {
    id: "c7_final_resolution",
    chapter: 7,
    scene: "office",
    backgroundKey: "panel_room",
    location: "최종 청문 회의실",
    speaker: "하린",
    text: "최종 결론으로 들어가기 직전이다. 공개 범위, 재발방지, 책임 범위를 한 문장으로 정리하자.",
    choices: [
      {
        choiceId: "c7_choice_censure",
        label: "결과 정합을 우선해 공식 결론 확정",
        subtext: "재확인 가능한 문장으로 마무리",
        next: "c7_verdict_censure",
        effects: { order: 2 },
        setFlags: { verdict_censure: true },
      },
      {
        choiceId: "c7_choice_reconciliation",
        label: "유감 완화 조치까지 함께 제시",
        subtext: "조직 신뢰를 함께 회복",
        next: "c7_verdict_reconciliation",
        effects: { empathy: 2, bond: 1 },
        setFlags: { verdict_reconciliation: true },
      },
      {
        choiceId: "c7_choice_reform",
        label: "중재형 결론으로 균형 있는 권고안 작성",
        subtext: "다음 분기까지 이어지는 규정화",
        next: "c7_verdict_reform",
        effects: { insight: 1, empathy: 1, order: 1, bond: 1 },
        setFlags: { verdict_reform: true },
      },
    ],
  },
  c7_verdict_censure: {
    id: "c7_verdict_censure",
    chapter: 7,
    scene: "office",
    backgroundKey: "censure_chamber",
    location: "징계 판정석",
    speaker: "하린",
    text: "공식 결론은 절차 위반과 기록 정합성 문제를 분리해 확정했다. 회복 조치는 후속 과제로 남지만, 책임 범위는 더 이상 흔들리지 않는다.",
    next: "resolve",
    setFlags: { verdict_censure: true },
    document: true,
  },
  c7_verdict_reconciliation: {
    id: "c7_verdict_reconciliation",
    chapter: 7,
    scene: "village",
    backgroundKey: "reconciliation_desk",
    location: "화해 기록 데스크",
    speaker: "해치",
    text: "유감 표명과 정정 절차가 같은 문장에 들어가자 방청석의 긴장이 낮아졌다. 기록은 처벌보다 회복을 먼저 읽히는 방식으로 닫힌다.",
    next: "resolve",
    setFlags: { verdict_reconciliation: true },
    document: true,
  },
  c7_verdict_reform: {
    id: "c7_verdict_reform",
    chapter: 7,
    scene: "maze",
    backgroundKey: "reform_blueprint",
    location: "재발방지 설계실",
    speaker: "나레이터",
    text: "중재형 권고안은 책임, 회복, 재발방지를 한 장의 운영 지침으로 묶었다. 이번 판정은 다음 사건의 기준선으로 남는다.",
    next: "resolve",
    setFlags: { verdict_reform: true },
    document: true,
  },


  end_balanced: {
    id: "end_balanced",
    chapter: 7,
    scene: "return",
    location: "보고 완료 데스크",
    speaker: "하치",
    text: "균형이 잡힌 판정이다. 규정과 사람의 맥락을 함께 반영해 사안을 안정적으로 정리했다.",
    document: true,
    ending: "balanced",
  },
  end_human: {
    id: "end_human",
    chapter: 7,
    scene: "return",
    location: "보고 완료 데스크",
    speaker: "하치",
    text: "공감 중심의 판정이다. 책임보다 회복을 우선했으나, 규정 개선의 책임은 별도 기록되었다.",
    document: true,
    ending: "human",
  },
  end_order: {
    id: "end_order",
    chapter: 7,
    scene: "return",
    location: "보고 완료 데스크",
    speaker: "하린",
    text: "절차 중심으로 단단히 마무리됐다. 규정 준수는 높지만, 관계 회복은 추후 과제로 남는다.",
    document: true,
    ending: "order",
  },
};

export const START_NODE = "c1_open";
export const EARLY_ROUTE_GATE_ROUTE = "early_route_gate";
export const MID_ROUTE_GATE_ROUTE = "mid_route_gate";
export const ROUTE_BRIDGE_ROUTE = "route_bridge";

const FINAL_VERDICT_WEIGHT = 2;

function countActiveFlags(flags: StoryFlagState, keys: StoryFlag[]) {
  return keys.reduce((total, key) => total + (flags[key] ? 1 : 0), 0);
}

export function getRouteFlagScores(flags: StoryFlagState = {}) {
  const orderRoute = countActiveFlags(flags, [
    "early_fact_path",
    "early_fact_recheck",
    "c3_design_time_axis_flag",
    "c3_final_fact_report",
    "c4_board_procedure",
    "c4_hearing_reliability_order",
    "c4_resolution_strict",
    "panel_censure",
    "prebrief_record_chain",
    "rumor_internal_discipline",
    "summary_internal_notice",
    "c5_frame_evidence_chain",
    "c7_panel_audit_record",
    "c7_cross_procedure_answer",
  ]);
  const humanRoute = countActiveFlags(flags, [
    "early_human_path",
    "early_human_recheck",
    "c3_design_relation_axis_flag",
    "c3_final_motive_report",
    "c4_board_witness",
    "c4_witness_trust_focus",
    "c4_press_repair_first",
    "c4_resolution_repair",
    "panel_reconciliation",
    "prebrief_witness_circle",
    "rumor_public_forum",
    "summary_public_trust",
    "c5_frame_testimony_context",
    "c7_panel_core_testimony",
    "c7_cross_recovery_answer",
  ]);
  const balancedRoute = countActiveFlags(flags, [
    "early_balance_path",
    "early_balance_recheck",
    "c3_final_balanced_report",
    "c4_board_public_risk",
    "c4_hearing_exception_prevention",
    "c4_witness_log_pair",
    "c4_press_reform_first",
    "c4_resolution_balanced",
    "panel_reform",
    "prebrief_rule_review",
    "rumor_media_strategy",
    "summary_followup_schedule",
    "c5_frame_public_balance",
    "c7_panel_expert_reform",
    "c7_cross_summary_answer",
  ]);
  return {
    orderRoute: orderRoute + (flags.verdict_censure ? FINAL_VERDICT_WEIGHT : 0),
    humanRoute: humanRoute + (flags.verdict_reconciliation ? FINAL_VERDICT_WEIGHT : 0),
    balancedRoute: balancedRoute + (flags.verdict_reform ? FINAL_VERDICT_WEIGHT : 0),
  };
}

export function resolveRouteBridge(flags: StoryFlagState = {}) {
  const { orderRoute, humanRoute, balancedRoute } = getRouteFlagScores(flags);
  if (orderRoute > humanRoute && orderRoute > balancedRoute) return "c7_bridge_order";
  if (humanRoute > orderRoute && humanRoute > balancedRoute) return "c7_bridge_human";
  if (balancedRoute > orderRoute && balancedRoute > humanRoute) return "c7_bridge_balanced";
  return "c7_bridge_mixed";
}

export function resolveEarlyRouteGate(flags: StoryFlagState = {}) {
  const { orderRoute, humanRoute, balancedRoute } = getRouteFlagScores(flags);
  if (orderRoute > humanRoute && orderRoute > balancedRoute) return "c3_entry_fact";
  if (humanRoute > orderRoute && humanRoute > balancedRoute) return "c3_entry_human";
  if (balancedRoute > orderRoute && balancedRoute > humanRoute) return "c3_entry_balanced";
  return "c3_entry_mixed";
}

export function resolveMidRouteGate(flags: StoryFlagState = {}) {
  const { orderRoute, humanRoute, balancedRoute } = getRouteFlagScores(flags);
  if (orderRoute > humanRoute && orderRoute > balancedRoute) return "c6_review_order_entry";
  if (humanRoute > orderRoute && humanRoute > balancedRoute) return "c6_review_human_entry";
  if (balancedRoute > orderRoute && balancedRoute > humanRoute) return "c6_review_balanced_entry";
  return "c6_review_mixed_entry";
}

export function resolveEnding(stats: StoryStats, evidenceCount: number, flags: StoryFlagState = {}) {
  const { orderRoute, humanRoute, balancedRoute } = getRouteFlagScores(flags);

  if (balancedRoute >= 3 && stats.insight >= 4 && stats.empathy >= 4 && stats.order >= 3 && evidenceCount >= 5)
    return "end_balanced";
  if (humanRoute >= 3 && stats.empathy + stats.bond >= stats.order + 1) return "end_human";
  if (orderRoute >= 3 && stats.order >= stats.empathy && stats.insight >= 4) return "end_order";
  if (stats.empathy >= stats.order + 3 && stats.bond >= 2) return "end_human";
  if (stats.insight >= 5 && stats.empathy >= 5 && stats.order >= 4 && stats.bond >= 2 && evidenceCount >= 5)
    return "end_balanced";
  if (stats.bond >= 4 && stats.empathy >= 4) return "end_human";
  if (stats.order > stats.empathy + 1 && stats.insight >= 4 && stats.bond < 3) return "end_order";
  if (stats.empathy + stats.bond > stats.order + 2) return "end_human";
  return "end_balanced";
}
